# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=30)),
                ('duration', models.IntegerField(max_length=30)),
                ('expire_date', models.DateField(default=datetime.date(2020, 6, 16))),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
