# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
